# --- Site settings ---
title: "Bofu Dong"
email: bofudong@iu.edu
description: >-
  PhD student in Data Science at IU Indianapolis.
url: "https://bofudong.com"   # if you're still testing on GitHub Pages only, set to your pages URL
baseurl: ""                    # keep empty when using a root custom domain
minimal_mistakes_skin: default
search: true
timezone: "America/Indiana/Indianapolis"

# --- Build settings ---
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:title/

include:
  - _pages

# --- Plugins (no blog pagination/feed needed) ---
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# --- Author (sidebar/header card) ---
author:
  name   : "Bofu Dong"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "PhD student at IU Indianapolis."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:bofudong@iu.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/desdai"

# --- Footer links ---
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:bofudong@iu.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/desdai"

# --- Defaults (no posts; set page defaults, then specific ones) ---
defaults:
  # All pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
      toc: false

  # Specific: About
  - scope:
      path: "_pages/about.md"
      type: pages
    values:
      layout: single
      author_profile: true

  # Specific: Activities
  - scope:
      path: "_pages/activities.md"
      type: pages
    values:
      layout: single
      author_profile: true

# --- Archives (disabled) ---
# (Remove category/tag archives since we don't use posts)
